/**
 * Writes the placeholder verification documents the seed references.
 *
 * `seed.sql` inserts ngo_documents rows pointing at `seed/doc-<type>.pdf`, but
 * nothing ever created those files — so the admin document viewer listed papers
 * that could not be opened, and adding a download link would have produced a
 * 404 rather than a document. This closes that gap.
 *
 * Reuses the receipt writer from M6 rather than shipping a second PDF path, so
 * these are genuinely valid PDFs an admin can click and read, not empty files
 * with a .pdf extension.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { renderPdf, type PdfBlock } from '../server/src/lib/pdf.ts'

const STORAGE_DIR = process.env.STORAGE_DIR ?? 'storage'

/** Every doc_type seed.sql references. */
const DOC_TYPES = [
  'registration_certificate',
  '80g_certificate',
  'darpan_listing',
  'pan_card',
] as const

function placeholder(docType: string): PdfBlock[] {
  const title = docType.replace(/_/g, ' ')

  return [
    { kind: 'text', text: 'EEGAI', font: 'bold', size: 26, gapAfter: 2 },
    { kind: 'text', text: 'Seed data - not a real document', size: 10, gapAfter: 14 },
    { kind: 'rule', gapAfter: 20 },

    { kind: 'text', text: title, font: 'bold', size: 16, gapAfter: 16 },

    {
      kind: 'text',
      text:
        'This file is a placeholder generated by `npm run db:reset` so that the admin ' +
        'verification queue has something real to open. It is not a certificate, it ' +
        'proves nothing, and no organisation should ever be verified on the strength of it.',
      gapAfter: 14,
    },
    {
      kind: 'text',
      text:
        'Document upload for organisations is not built yet. When it is, these seeded rows ' +
        'should be replaced by genuinely uploaded files and this script deleted.',
      gapAfter: 14,
    },

    { kind: 'rule', gapAfter: 14 },
    { kind: 'text', text: `Type: ${docType}`, font: 'mono', size: 10 },
  ]
}

const directory = join(STORAGE_DIR, 'seed')
await mkdir(directory, { recursive: true })

for (const docType of DOC_TYPES) {
  const pdf = renderPdf(placeholder(docType), `EEGAI seed - ${docType}`)
  await writeFile(join(directory, `doc-${docType}.pdf`), pdf)
}

console.log(`  ${DOC_TYPES.length} seed documents written to ${directory}/`)
